version: '3.8'
services:
  test-sprt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 8g
    volumes:
      - ./output:/app/output
      - ./engines:/app/engines
      - ./sprt_presets.ini:/app/sprt_presets.ini
    command: ["1.0", "1.0-SNAPSHOT", "fast"] # Parameters for test_sprt.sh
