FROM --platform=linux/amd64 ubuntu:22.04

WORKDIR /app

# Install required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    libqt5core5a libqt5widgets5 libqt5gui5 \
    ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*